### ISSUE TITLE
Robot droops down after attaching weight

### ISSUE THREAD

**Issue by simonschmeisser** [kroshu/kuka-external-control-sdk#13]
When I try to pick any object (ca 0.4kg with 11kg iisy, suction or gripper) the robot will behave in weird ways. Best case it will just droop down a bit and go into protective stop. Sometimes it also returns to the gripping point after having lifted it up and tries to lift it again. Sometimes it drops pretty far after having lifted the piece to the expected height.

procedure is:
turn suction on
move to gripping/suction point
part is lifted up a bit by suction/ stays at rest with 2 finger gripper
now robot is at rest
send new trajectory from expected point after gripping to lift it up
weird things happen

My understanding is there is absolutely no way to set the payload but it is very much required for the control algorithm? Not even from a capability?

Are there settings I could tune to make control more robust/reactive? I experimented with overestimating tool weight (2.5 to 2.8kg, depending on which is mounted) to 3kg or 3.2kg but it did not help much

Would it be possible to get beta/alpha versions where payload is accessible? simon.schmeisser@optonic.com we do have a NDA with Kuka

For a recording of a particularly strange motion please see here: https://share.optonic.com/s/EHcxYJx5SboQGzw

We use ros_control (ROS 1) and the JointTrajectoryController in Position mode. Do you expect better results for velocity or effort control mode? Do you have recommendations for PID values.

We wanted to show this robot at a fair Wednesday but currently it does not look like we can do this. Would be super grateful for any ideas!

**Comment by Svastits** [comment]
Could you please clarify a little more what exactly happens in which case? Do you run exactly the same code in each case, resulting in different weird movements? How exactly do command the robot? do you use moveit connected to the JointTrajectoryController? 

I will try to answer your questions:
- Unfortunately it is not possible to set the payload externally... BUT in my opinion this 0.4kg change should not really cause such issues, the control algorithm should definitely compensate for the load difference. For example if you try to push a robot by hand, which is certainly more force, than 400g, it will not move from standstill. (The only thing that could occur in position mode is that collision detection is triggered in safety due to the incorrectly configured load, you can disable this is the safety configuration.)
- I would definitely stick to position control (there is no velocity control, but joint impedance control instead, are you sure you are not using that? in that mode the incorrectly configured load causes dropping). Torque mode is much more complex, and it should work in position mode...

Could you somehow log the position values sent to the robot and compare these with the measured joint positions? That might help debugging this issue further.

**Comment by simonschmeisser** [comment]
We managed to get this working in the end by:

- handing over dense trajectories to ros_control
- switching to low latency kernel
- disabling safety

but sending dense trajectories solved most problems
